const categories = [
  { name: "Starlink", category: 52 },
  { name: "Geostationary", category: 10 },
  { name: "OneWeb", category: 53 },
  { name: "Iridium", category: 15 },
  { name: "Weather", category: 3 },
  { name: "TV", category: 34 },
  { name: "ISS", category: 2 },
  { name: "Chinese Space Station", category: 54 },
  { name: "Military", category: 30 },
  { name: "Education", category: 29 },
  { name: "Engineering", category: 28 },
  { name: "Search & rescue", category: 7 },
  { name: "Space & Earth Science", category: 26 },
  { name: "Amateur radio", category: 18 },
  { name: "Beidou Navigation System", category: 35 },
  { name: "Brightest", category: 1 },
  { name: "Celestis", category: 45 },
  { name: "CubeSats", category: 32 },
  { name: "Disaster monitoring", category: 8 },
  { name: "Earth resources", category: 6 },
  { name: "Experimental", category: 19 },
  { name: "Flock", category: 48 },
  { name: "Galileo", category: 22 },
  { name: "Geodetic", category: 27 },
  { name: "GPS Constellation", category: 50 },
  { name: "GPS Operational", category: 20 },
  { name: "Globalstar", category: 17 },
  { name: "Glonass Constellation", category: 51 },
  { name: "Glonass Operational", category: 21 },
  { name: "GOES", category: 5 },
  { name: "Gonets", category: 40 },
  { name: "Gorizont", category: 12 },
  { name: "Intelsat", category: 11 },
  { name: "IRNSS", category: 46 },
  { name: "Lemur", category: 49 },
  { name: "Molniya", category: 14 },
  { name: "Navy Navigation Satellite System", category: 24 },
  { name: "NOAA", category: 4 },
  { name: "O3B Networks", category: 43 },
  { name: "Orbcomm", category: 16 },
  { name: "Parus", category: 38 },
  { name: "QZSS", category: 47 },
  { name: "Radar Calibration", category: 31 },
  { name: "Raduga", category: 13 },
  { name: "Russian LEO Navigation", category: 25 },
  { name: "Satellite-Based Augmentation System", category: 23 },
  { name: "Strela", category: 39 },
  { name: "Tracking and Data Relay Satellite System", category: 9 },
  { name: "Tselina", category: 44 },
  { name: "Tsikada", category: 42 },
  { name: "Tsiklon", category: 41 },
  { name: "Westford Needles", category: 37 },
  { name: "XM and Sirius", category: 33 },
  { name: "Yaogan", category: 36 },
];

export default categories;
